//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string TypeOfOperation { get; set; }
        public Nullable<int> CleintId { get; set; }
        public Nullable<int> RealtyId { get; set; }
        public Nullable<int> RealtorsId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual Realty Realty { get; set; }
    }
}
